version = 1
SPDX-PackageName = "fair-python-cookiecutter-demo"
SPDX-PackageSupplier = "Anton Pirogov <a.pirogov@fz-juelich.de>"
SPDX-PackageDownloadLocation = "https://github.com/Materials-Data-Science-and-Informatics/fair-python-cookiecutter-demo"

[[annotations]]
path = [".gitignore", "pyproject.toml", "poetry.lock", ".pre-commit-config.yaml", "codemeta.json", "CITATION.cff", "README.md", "RELEASE_NOTES.md", "CHANGELOG.md", "CODE_OF_CONDUCT.md", "AUTHORS.md", "CONTRIBUTING.md", ".gitlab-ci.yml", ".gitlab/**", ".github/**", "mkdocs.yml", "docs/**", "somesy.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2025 Forschungszentrum Jülich GmbH - Institute for Materials Data Science and Informatics (IAS9) - Stefan Sandfeld <s.sandfeld@fz-juelich.de>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/fair_python_cookiecutter_demo/**", "tests/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2025 Forschungszentrum Jülich GmbH - Institute for Materials Data Science and Informatics (IAS9) - Stefan Sandfeld <s.sandfeld@fz-juelich.de>"
SPDX-License-Identifier = "Unlicense"
